site_name: Rocket EVE
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: "blue grey"
    accent: "blue"
  icon:
    logo: bootstrap/rocket-takeoff-fill
  favicon: img/rocket-takeoff-fill.svg  
nav: 
  - Launch Updates: index.md
  - About: about.md
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons